spring:
  datasource:
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    url: jdbc:mysql://localhost:3306/jwt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${SECRET_KEY}
    time:
      access-expiration: 3600000      # 1 hour (ms)
      refresh-expiration: 2592000000  # 30 days (ms)